# Generated by Django 4.2.3 on 2023-08-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=30)),
                ('Teacher_Number', models.CharField(max_length=50)),
                ('Name_of_parish', models.CharField(max_length=30)),
                ('Choice_of_competition', models.CharField(choices=[('spoken word', 'spoken word'), ('bible quiz', 'bible quiz'), ('Both', 'Both')], max_length=30)),
            ],
        ),
    ]
